### ISSUE TITLE
error when executing on F5

### ISSUE THREAD

**Issue by patdha86** [f5regan/o365-apm-split-tunnel#5]
Any idea why am I getting error when executing script on F5 (running version 14.1.4)
Traceback (most recent call last):
  File "apm_o365_update.py", line 392, in <module>
    main()
  File "apm_o365_update.py", line 209, in main
    conn.request('GET', request_string)
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1236, in connect
    server_hostname=sni_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 833, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

**Comment by f5regan** [comment]
Hello, this error indicates a failure to verify the issuer of the certificate presented by the O365 web service. httplib uses the system CA certificate bundle (/config/ssl/ssl.crt/ca-bundle.crt) as its trusted root store. I just checked 14.1.4.0 and 14.1.4.1 and I was unable to reproduce the issue with the built-in bundle. I would guess that either the certificate bundle on your system has been modified in such a way that trust for the CA that signed the endpoints.office.com certificate has been removed/revoked or the BIG-IP is communicating through a proxy that is doing TLS intercept / forging the real cert and signing it with an subordinate from your internal PKI.

Try issuing this command from the CLI of the BIG-IP and see what you get back:

curl -v https://endpoints.office.com/

You should see something like this:

```
* Server certificate:
*        subject: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; CN=endpoints.office.com
*        start date: Oct 15 04:16:43 2020 GMT
*        expire date: Nov 16 04:16:43 2021 GMT
*        issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Organization Validation CA - SHA256 - G3
*        SSL certificate verify ok.
```

If you see a different issuer (ex. your organization's name) or this error:

`*        SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.`

then we can be pretty sure your bundle doesn't include the necessary root/intermediate certificates needed by your system to establish trust.

This knowledge article provides some information about how to update the built-in CA bundle using the bundle manager (bottom of the page): 

K60612439: Manually updating the BIG-IP default CA certificate bundle file
https://support.f5.com/csp/article/K60612439

Hope that helps!
